---
title: сapitulum II
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(checkdown)
```

_Insere formam imperfecti_.

1. Orgetorix, M. Messala, M. Pisone consulibus, regni cupiditate inductus coniurationem nobilitatis fecit et civitati persuasit ut de finibus suis cum omnibus copiis  __________ (exeo): perfacile esse, cum virtute omnibus  __________ (praesto), totius Galliae imperio potiri.
`r check_question(answer = c('exirent', 'exirent'), button_label = 'corrigere', right = '✅', wrong = '❌') `
`r check_hint('exirent', hint_title = '_vide responsum_') `
`r check_question(answer = c('praestarent', 'praestarent'), button_label = 'corrigere', right = '✅', wrong = '❌') `
`r check_hint('praestarent', hint_title = '_vide responsum_') `


2. His rebus fiebat ut et minus late  __________ (vagor) et minus facile finitimis bellum inferre __________ (possum).
`r check_question(answer = c('vagarentur', 'vagarentur'), button_label = 'corrigere', right = '✅', wrong = '❌') `
`r check_hint('vagarentur', hint_title = '_vide responsum_') `
`r check_question(answer = c('possent', 'possent'), button_label = 'corrigere', right = '✅', wrong = '❌') `
`r check_hint('possent', hint_title = '_vide responsum_') `

3. Pro multitudine autem hominum et pro gloria belli atque fortitudinis angustos se fines habere  __________ (arbitror), qui in longitudinem milia passuum CCXL, in latitudinem CLXXX __________ (pateo).
`r check_question(answer = c('arbitrabantur', 'arbitrabantur'), button_label = 'corrigere', right = '✅', wrong = '❌') `
`r check_hint('arbitrabantur', hint_title = '_vide responsum_') `
`r check_question(answer = c('patebant', 'patebant'), button_label = 'corrigere', right = '✅', wrong = '❌') `
`r check_hint('patebant', hint_title = '_vide responsum_') `
