project:
  type: website
  output-dir: ./docs
website:
  navbar:
    title: "De Bello Gallico, Liber I"
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: "Domus"
      - href: capitulum_1.qmd
      - href: capitulum_2.qmd
      - href: capitulum_3.qmd
      - href: capitulum_4.qmd
      - href: capitulum_5.qmd
      - href: capitulum_6.qmd
      - href: capitulum_7.qmd
      - href: capitulum_8.qmd
      - href: capitulum_9.qmd
      - href: capitulum_10.qmd
      - href: capitulum_11.qmd
      - href: capitulum_12.qmd
      - href: capitulum_13.qmd
      - href: capitulum_14.qmd
      - href: capitulum_15.qmd
      - href: capitulum_16.qmd
      - href: capitulum_17.qmd
      - href: capitulum_18.qmd
format:
  html:
    theme: sandstone
    toc: false
    css: include/webex.css
    include-after-body: include/webex.js
  pdf:
    toc: false
    include-in-header:
      text: |
        \pagenumbering{gobble}

format-links: [pdf]
