---
title: capitulum I
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

(@) Gallia est omnis divisa in partes tres, `r fitb('quarum', ignore_case = TRUE)` _(qui, quae, quod)_ unam incolunt Belgae, aliam Aquitani, tertiam `r fitb('qui', ignore_case = TRUE)` _(qui, quae, quod)_ ipsorum lingua Celtae, nostra Galli appellantur.

(@) Horum omnium fortissimi sunt Belgae, propterea quod a cultu atque humanitate provinciae longissime absunt, minimeque ad eos mercatores saepe commeant atque ea `r fitb('quae', ignore_case = TRUE)` _(qui, quae, quod)_ ad effeminandos animos pertinent important, proximique sunt Germanis, `r fitb('qui', ignore_case = TRUE)` _(qui, quae, quod)_ trans Rhenum incolunt, `r fitb('quibus', ignore_case = TRUE)` _(qui, quae, quod)_ cum continenter bellum gerunt.


(@) `r fitb('qua', ignore_case = TRUE)` _(qui, quae, quod)_ de causa Helvetii quoque reliquos Gallos virtute praecedunt, quod fere cotidianis proeliis cum Germanis contendunt, cum aut suis finibus eos prohibent aut ipsi in eorum finibus bellum gerunt.


(@) Eorum una pars, `r fitb('quam', ignore_case = TRUE)` _(qui, quae, quod)_ Gallos obtinere dictum est, initium capit a flumine Rhodano, continetur Garumna flumine, Oceano, finibus Belgarum, attingit etiam ab Sequanis et Helvetiis flumen Rhenum, vergit ad septentriones.

(@) Aquitania a Garumna flumine ad Pyrenaeos montes et eam partem Oceani `r fitb('quae', ignore_case = TRUE)` _(qui, quae, quod)_ est ad Hispaniam pertinet.
