---
title: capitulum VII
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

(1) Caesari cum id nuntiatum esset, eos per provinciam nostram iter facere conari, `r fitb("maturat")` _(= mature it, properat)_ ab urbe proficisci et quam maximis potest itineribus in Galliam `r fitb("ulteriorem")` _(= ultra Alpes)_ contendit et ad Genavam pervenit. 

(2) `r fitb(c("Provinciae toti", "provinciae toti"))` _(provincia tota, dat.)_ quam maximum potest militum numerum imperat (erat omnino in Gallia ulteriore legio una), pontem, qui erat ad Genavam, iubet `r fitb("rescindi")` _(= rumpi; < scindo)_. 

(3) Ubi de eius adventu Helvetii certiores facti sunt, legatos ad eum mittunt nobilissimos _civitatis_ (a), cuius legationis Nammeius et Verucloetius principem locum obtinebant, qui `r fitb("dicerent")` _(dico, impf. coni. act.)_ sibi esse in animo sine ullo `r fitb("maleficio")` _(↔︎  beneficio)_ iter per provinciam facere, propterea quod aliud iter haberent nullum: rogare ut eius voluntate id sibi facere liceat. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (3a): genetivus `r fitb("partitivus")`.

(4) Caesar, quod memoria tenebat L. Cassium consulem occisum exercitumque eius ab Helvetiis pulsum et sub iugum missum, concedendum non putabat; neque homines _inimico animo_ (a), data facultate per provinciam itineris `r fitb("faciundi")` _(= faciendi)_, temperaturos `r fitb("ab")` _(de/ab/ex/sine)_ iniuria et maleficio existimabat. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (4a): ablativus `r fitb("qualitatis")`

(5) Tamen, ut spatium intercedere posset dum milites quos imperaverat convenirent, legatis respondit diem se ad deliberandum sumpturum: si quid vellent, ad Id. April. `r fitb("reverterentur")` _(revertor, impf. coni.)_. 