---
title: capitulum IX
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


(1) Relinquebatur una per Sequanos via, qua _Sequanis invitis_ (a)  propter angustias ire non poterant. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(1a): ablativus `r fitb("absolutus")`.


(2) His cum sua sponte persuadere non possent, legatos ad Dumnorigem Haeduum mittunt, ut _eo deprecatore_ (a) a Sequanis impetrarent.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(2a): ablativus `r fitb("absolutus")`.


(3) Dumnorix _gratia et largitione_ (a) apud Sequanos  plurimum poterat et Helvetiis erat amicus, quod ex ea civitate Orgetorigis filiam in matrimonium duxerat, et, cupiditate _regni_ (b)  adductus, novis rebus studebat et quam plurimas civitates suo beneficio habere obstrictas volebat.


&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(3a): ablativus `r fitb("causae")`.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(3b): genetivus `r fitb(c("obiectivus", "obiecti", "objecti", "objectivus"))`.


(4) Itaque rem suscipit et a Sequanis impetrat ut per fines suos Helvetios ire patiantur, obsidesque uti inter sese dent perficit: Sequani, ne _itinere_ (a) Helvetios prohibeant, Helvetii, ut sine maleficio et iniuria transeant.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(4a): ablativus `r fitb("separationis")`.
