---
title: capitulum XI
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


(1) Helvetii iam per angustias et fines Sequanorum suas copias `r fitb('traduxerant')` _(traduco; pqpf. ind. act.)_ et in Haeduorum fines `r fitb('pervenerant')` _(pervenio; pqpf. ind. act.)_ eorumque agros populabantur. 


(2) Haedui, cum se suaque ab iis defendere non `r fitb('possent')` _(possum; impf. coni. act.)_, legatos ad Caesarem mittunt `r fitb(c('rogatum auxilium', 'auxilium rogatum'))` _(= ut rogent auxilium; ad auxilium rogandum)_: ita se omni tempore `r fitb("de")` _(a/cum/de/sine)_ populo Romano meritos esse ut paene in conspectu exercitus nostri agri vastari, liberi eorum in servitutem abduci, oppida expugnari non `r fitb("debuerint")` _(debeo, perf. coni.)_. 

(3) Eodem tempore Ambarri, `r fitb('necessarii')` _(= familiares)_ et consanguinei Haeduorum, Caesarem `r fitb('certiorem')` _(< certus)_ faciunt sese depopulatis agris non facile ab oppidis vim hostium prohibere. 

(4) Item Allobroges, qui trans Rhodanum vicos possessionesque habebant, fuga se ad Caesarem recipiunt et demonstrant sibi praeter agri `r fitb('solum')` _(= terram)_ nihil esse _reliqui_ (a). 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (4a): genetivus `r fitb("generis")`.

(5) Quibus rebus adductus Caesar `r fitb(c('non expectandum', 'non expectandum esse'))` _(💬 "non debeo expectare"; coni. periphrastica)_ sibi statuit dum, omnibus fortunis sociorum consumptis, in Santonos Helvetii `r fitb('pervenirent')` _(pervenio; impf. coni.)_. 