---
title: capitulum XIII
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


(1) Hoc proelio facto reliquas copias Helvetiorum _ut_ (a) consequi posset, pontem in Arari _faciendum_ (b) curat atque ita exercitum traducit.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (1a): ut `r fitb("finale")`.
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (1b): participium `r fitb("futuri")` passivi.

(2) Helvetii repentino eius adventu commoti cum id quod ipsi _diebus viginti_ (a) `r fitb("aegerrime")` _(︎<=︎> facillime; < aeger)_ `r fitb("confecerant")` _(conficio, pqpf. ind. act.)_, ut flumen `r fitb("transirent")` _(transeo, impf. coni. act.)_, illum uno die fecisse `r fitb("intellegerent")` _(intellego, impf. coni. act.)_, legatos ad eum mittunt; `r fitb("cuius")` _(qui, qua, quod)_ legationis Divico princeps fuit, qui bello Cassiano dux Helvetiorum fuerat. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (2a): ablativus `r fitb("temporis")`.

(3) Is ita cum Caesare egit: si pacem populus Romanus cum Helvetiis `r fitb("faceret")`, in eam partem `r fitb("ituros")` atque ibi `r fitb("futuros")` Helvetios ubi eos Caesar `r fitb("constituisset")` atque esse `r fitb("voluisset")`; sin bello persequi `r fitb("perseveraret")`, `r fitb("reminisceretur")` et veteris incommodi populi Romani et pristinae virtutis Helvetiorum. 

> **Divico**: "Si pacem populus Romanus nobiscum *facit*, in eam partem *ibimus* atque ibi *erimus* ubi nos tu *constitueris* atque esse *volueris*; si bello nos persequi *perseveras*, *reminiscere*...!"

(4) Quod `r fitb("improviso")` _(= subito, repente; < provideo)_ unum pagum `r fitb("adortus esset")` _(adorior, pqpf. coni. pass.)_, cum ii qui flumen transissent suis auxilium ferre non possent, ne ob eam rem aut suae magnopere virtuti `r fitb("tribueret")` aut ipsos `r fitb("despiceret")`. 

> **Divico**: "...Noli aut tuae virtuti magnopere *tribuere* aut nos *despicere*!"

(5) Se ita a patribus maioribusque suis didicisse, ut magis virtute `r fitb("contenderent")` _(= certarent; < tendo)_ quam dolo aut insidiis `r fitb("niterentur")` _(= uterentur)_.


(6) Quare ne committeret ut is locus ubi constitissent ex `r fitb("calamitate")` _(︎<=> victoria)_ populi Romani et internecione exercitus nomen caperet aut memoriam proderet. 