---
title: capitulum XII
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


(1) Flumen est Arar, quod per fines Haeduorum et Sequanorum in Rhodanum influit, _incredibili lenitate_ (a), ita ut oculis in utram partem fluat iudicari non possit. Id Helvetii ratibus ac `r fitb("lintribus")` _(=naviculis levibus)_ iunctis transibant. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (1a): ablativus `r fitb("qualitatis")`.


(2) Ubi per exploratores Caesar certior factus est tres iam partes copiarum Helvetios `r fitb("id flumen traduxisse")` _(=trans id flumen duxisse)_, quartam vero partem `r fitb("citra")` _(↔︎ ultra)_ flumen Ararim reliquam esse, de tertia vigilia cum legionibus tribus e castris profectus ad eam partem pervenit quae `r fitb("nondum")` _(numquam/ /nondum/iam/necdum)_ flumen transierat. 

(3) Eos `r fitb("impeditos")` _(︎<=> expeditos; <  impedio)_ et `r fitb("inopinantes")` _(= non expectantes; < opinor)_ adgressus magnam partem eorum concidit; reliqui sese fugae mandarunt atque in proximas silvas `r fitb("abdiderunt")` _(=occultaverunt; < do)_. 

(4) Is pagus appellabatur Tigurinus; nam omnis civitas Helvetia in quattuor pagos divisa est. Hic pagus unus, cum domo exisset, patrum nostrorum _memoria_ (a) L. Cassium consulem interfecerat et eius exercitum sub iugum miserat. 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; (4a): ablativus `r fitb("temporis")`.

(5) Ita sive casu sive consilio deorum immortalium quae pars civitatis Helvetiae `r fitb("insignem")` _(= magnam et notam; < signum)_ calamitatem populo Romano intulerat, ea princeps poenam persolvit. Qua in re Caesar non solum publicas, sed etiam privatas iniurias `r fitb("ultus est")` _(ulciscor, pf. ind. pass.)_, quod eius soceri L. Pisonis avum, L. Pisonem legatum, Tigurini eodem proelio quo Cassium interfecerant. 